config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :posts do
    resources :comments
  end
  resources :users, except: [:new, :create]
  get "/generate", to: "posts#generate"
  root "pages#main"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/main.html.erb
<p>
  <h1> Welcome to my blog <%= @current_user ? @current_user.username : "" %> !</h1>
</p>
<h2> Below are the 5 latest posts:</h2>

<%= will_paginate @posts %>
<table>
  <th> POST NAME </th>
  <th> POST BODY </th>
  <% @posts.each do |post| %>
  <tr>
    <td><%= link_to post.title, post %></td>
    <td><%= post.body %></td>
    <td><%= link_to "Edit", edit_post_url(post.id) %> </td>
    <td><%= link_to "Destroy", post, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
  </tr>
  <% end %>
</table>

<% if @current_user %>
<%= link_to "logout", "/logout" %>
<% else %>
<%= link_to "login", "/login" %>
<%= link_to "signup", "/signup" %>
<% end %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>